In [1]:
import tensorflow as tf

In [2]:
#load and prepare handwrite dataset MNIST
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
#Convert the samples from integers to floating-point numbers
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
#Stacking layers with tf.keras.sequential
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
#For each example the model returns a vector of "logits" or "log-odds" scores, one fro each class.
#"logits": The vector of raw(non-normalized) predictions that a classification model generates, which is ordinarily then passed to a normalization function
predictions=model(x_train[:1]).numpy()
predictions

array([[-0.16406414,  0.5323777 ,  0.23581801, -0.20124906,  0.37607884,
         0.16601942,  0.24264139,  0.2612751 , -1.2117939 ,  0.07492875]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07563291, 0.15176502, 0.11281775, 0.07287215, 0.12980516,
        0.10521176, 0.11359018, 0.11572663, 0.02652697, 0.09605149]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.25178

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
# Model.fit method adjusts the model parameters to minimize the loss
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 501us/step - loss: 0.2903 - accuracy: 0.91590s - los
Epoch 2/5
1875/1875 [==============================] - 1s 497us/step - loss: 0.1423 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 1s 489us/step - loss: 0.1091 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 1s 492us/step - loss: 0.0869 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 1s 490us/step - loss: 0.0753 - accuracy: 0.9765


In [10]:
# The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set"
# "Validation-set": A subset of the dataset-disjoint from the training set-used in validation
# "Test-set": The subset of the dataset that you use to test your model after the model has gone through initial vetting by the calidation set
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0767 - accuracy: 0.9761


[0.07671293616294861, 0.9761000275611877]

In [11]:
# Stack one more layer "softmax" to return a probability 
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.50353083e-06, 1.67556866e-08, 4.72604625e-05, 2.43833827e-04,
        1.51363894e-10, 1.00645394e-07, 7.28237783e-12, 9.99700069e-01,
        2.10894427e-06, 5.18780689e-06],
       [7.93964077e-08, 3.17489066e-05, 9.99966979e-01, 1.16182082e-06,
        3.59626764e-16, 1.18230536e-08, 7.42100825e-09, 5.98782075e-15,
        2.32962116e-09, 6.13454600e-14],
       [9.97810730e-06, 9.96316552e-01, 1.49815134e-03, 1.01838246e-04,
        3.07188493e-05, 5.21967486e-05, 1.70283529e-04, 1.38122705e-03,
        4.31863795e-04, 7.21054994e-06],
       [9.99959826e-01, 3.58427088e-09, 2.10370326e-05, 2.94366735e-08,
        7.76663001e-09, 4.53561682e-07, 1.04774035e-05, 3.20714349e-07,
        2.61019295e-09, 7.83128871e-06],
       [4.45586920e-06, 8.66842331e-09, 7.68034351e-06, 1.97442880e-08,
        9.97276843e-01, 6.11160374e-07, 1.46676111e-05, 1.18743490e-04,
        1.63840843e-06, 2.57539516e-03]], dtype=float32)>